name: Run Angular Tests and Generate Coverage Report

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ] 

jobs:
  angular-test-and-coverage:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Angular dependencies
      working-directory: Client
      run: npm ci

    - name: Run Angular tests with coverage
      working-directory: Client
      env:
        NODE_OPTIONS: --openssl-legacy-provider
      run: |
        npx ng test --browsers=ChromeHeadless --watch=false --code-coverage
        echo "Angular tests completed."

    - name: Upload Angular Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: angular-code-coverage-report
        path: Client/coverage/client
